### ISSUE TITLE
Absence of `GrailQA/evaluate.py` 

### ISSUE THREAD

**Issue by midannii** [awslabs/decode-answer-logical-form#1]
Hi. 

When I run https://github.com/awslabs/decode-answer-logical-form/blob/main/DecAF/Datasets/QA/evaluate.py with the below code, 

```
cd DecAF-main/DecAF/Datasets/QA
SAVE_DIR='/home/midannii/midannii/DecAF-main/DecAF'
python evaluate.py --dataset GrailQA --result_path ${SAVE_DIR}/Reading/FiD/QA_GrailQA_Freebase_BM25_large_100_p100_b10/final_output_dev_fid_SPQA.json
```

I face the error that "python: can't open file 'GrailQA/evaluate.py': [Errno 2] No such file or directory" in https://github.com/awslabs/decode-answer-logical-form/blob/main/DecAF/Datasets/QA/evaluate.py#L88

I think `evaluate.py` should be add in `https://github.com/awslabs/decode-answer-logical-form/blob/main/DecAF/Datasets/QA/GrailQA`.

**Comment by PlusRoss** [comment]
Please see the [README](https://github.com/awslabs/decode-answer-logical-form/blob/main/DecAF/Datasets/QA/GrailQA/README.md). You need to download the official [evaluate.py](https://worksheets.codalab.org/bundles/0x2d13989c17e44690ab62cc4edc0b900d/) and put it in the GrailQA folder.
